# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10edbe9b6488ad4efc42121ec309bdddea52c4b8bbc7d1be7a21cf303714ad9652e0ff65d7b903d6fc5129445b1d4ab9ada0545618bbae7adc89b17366d73c11
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
test:
  secret_key_base: 940e36280a6dbbb6ce1bb60156a322ced3bc414ff6f8ba6c4fed5e20bf69f2c44d0eb4d625f079f8ab7ae0d65450c0141d9338a2ef57b3bb33a29f5373d5bad5
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
